### ISSUE TITLE
Feature Request: Consistent reaction time at different song speeds

### ISSUE THREAD

**Issue by ghost** [zeph-yr/JDFixer#11]
Reaction time seems to be affected by the speed of the song.
Slowing down the song will make the reaction time longer than desired, and speeding up the song will make it shorter.
It would be nice to have the option to keep a constant reaction time regardless of the speed of the song modified by modifiers (Slower Song, Faster Song, Super Fast Song), practice mode, PracticePlugin, etc.

**Comment by zeph-yr** [comment]
Hihi thanks for the suggestion. I'll look into it for the next release

**Comment by zeph-yr** [comment]
Done! 😁

**Comment by ghost** [comment]
Thank you for implementing it!
However, I found a problem - it doesn't seem to recognize speed changes in the PracticePlugin pause menu.
To reproduce it, start the song at 200% speed and change it to 100% in the pause menu. This makes the reaction time longer than desired.
