### ISSUE TITLE
Setting automated preferences doesn't work and softlocks the game

### ISSUE THREAD

**Issue by PnfrlEnm** [zeph-yr/JDFixer#18]
Automated JD preferences no longer work even if you have the config for them already in the JSON. Attempting to change them in game will just yeet the mods menu, change nothing else, and make every other UI button unclickable thus forcing you to manually restart the game

Log file is attached, please let me know if you need any other files 🥺👉👈
[_latest.log](https://github.com/zeph-yr/JDFixer/files/14470394/_latest.log)

**Comment by zeph-yr** [comment]
Thanks for reporting this. Fixed in https://github.com/zeph-yr/JDFixer/releases/tag/v7.2.4 and higher
