### ISSUE TITLE
Notes sometimes don't appear in TA

### ISSUE THREAD

**Issue by AsoDesu** [zeph-yr/JDFixer#2]
Sometimes when players in TA use JDFixer, the notes will not spawn in.

Upon further testing i'm sure that this may be a JDFixer issue, 
The mod logs this error into logs:

[CRITICAL @ 18:36:43 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 18:36:43 | UnityEngine] JDFixer.SpawnMovementDataUpdatePatch.Prefix (System.Single& startNoteJumpMovementSpeed, System.Single startBpm, System.Single& noteJumpStartBeatOffset, BeatmapObjectSpawnMovementData& __instance, System.Boolean& __state) (at <1473c895e5404107891407dbe68747ec>:0)
[CRITICAL @ 18:36:43 | UnityEngine] (wrapper dynamic-method) BeatmapObjectSpawnMovementData.BeatmapObjectSpawnMovementData.Init_Patch2(BeatmapObjectSpawnMovementData,int,single,single,single,single,UnityEngine.Vector3,UnityEngine.Vector3)
[CRITICAL @ 18:36:43 | UnityEngine] BeatmapObjectSpawnController.Start () (at <ed5f1dff68954975944aebd4c110b7aa>:0)

Here is the total log from when this error happened:
[2021.07.11.18.32.42.log](https://github.com/zeph-yr/JDFixer/files/6797389/2021.07.11.18.32.42.log)

**Comment by zeph-yr** [comment]
Thank you so much Aso for this log and the info you provided. The bug was introduced by the PR. It's been fixed now :)
