### ISSUE TITLE
JDFixer for 1.38.0?

### ISSUE THREAD

**Issue by xFixxTwT-official** [zeph-yr/JDFixer#20]
Hey, i just wanted to ask if the mod gets updated soon for 1.38.0 :)

if i use the v7.2.6 the game has just a black screen

**Comment by StratorX** [comment]
I would need this as well :)

**Comment by zeph-yr** [comment]
Thanks, it available now in https://github.com/zeph-yr/JDFixer/releases/tag/v7.3.0
