### ISSUE TITLE
Mod failed after upgrade to 1.17.0 with old settings file

### ISSUE THREAD

**Issue by karghoff-e** [zeph-yr/JDFixer#4]
Seems that a new mod version has additional fields in config file. 
That caused an error on read plugin configuration action if the old configuration still present in UserData folder.
Please see a log file attached.
[latest.log](https://github.com/zeph-yr/JDFixer/files/7101704/latest.log)

**Comment by zeph-yr** [comment]
Oh yep thanks for reminding me xD I forgot write this in the instructions, that you need re-do your preferences in-game or copy the corresponding json data to the new config file generated cuz the new mod is not compatible with the old one. Will update the instructions and release notes :)
