### ISSUE TITLE
JDFixer not working on some maps

### ISSUE THREAD

**Issue by Paini** [zeph-yr/JDFixer#7]
JDFixer is not adjusting the jump distance on some maps, but base game static JD adjustment is working on those maps.
Maybe a problem with low bpm and high njs maps again?

Example map: https://beatsaver.com/maps/10cc6

**Comment by yuvalmon** [comment]
Looks like version 3.0.1 changed the minimum HJD to the old one (before the base game changes), so the min JD is wrong?

**Comment by Shurdoof** [comment]
Looks like version 3.0.1 changed the minimum HJD to the old one (before the base game changes), so the min JD is wrong?

**Comment by zeph-yr** [comment]
Yes, 3.0.1 has the limit back at 1. The JD display is correct: it is true that some maps' defaults are now closer while others' are farther compared in previous game versions (and for 99% of the maps, nothing changed). This is the new definition of JD.

**Comment by Shurdoof** [comment]
So did this bring back the bpm locking for under ~120 bpm then?

**Comment by zeph-yr** [comment]
Yep Bpm lock is back for JD
