### ISSUE TITLE
Request: LevelTweaks functionality?

### ISSUE THREAD

**Issue by because-bot-fed** [zeph-yr/JDFixer#8]
Not sure LevelTweaks is being updated anymore, and it'd be nice to have an all-in-one solution.

If the mechanisms LevelTweaks uses are simple enough to copy or recreate, would you consider adding that to JDFixer? 

(I'm going to keep playing around with JDFixer and seeing how I like it, but I really miss the way LevelTweaks worked and I feel lost without it.) 

Totally selfish request and I understand if you're not interested, but if you were willing it would be greatly appreciated :)

**Comment by zeph-yr** [comment]
Hi thanks for reaching out, however I don't feel it would be appropriate to recreate LevelTweaks in JDFixer. You can reach out to the author of LT and ask if he will be updating it :)

**Comment by because-bot-fed** [comment]
Totally understand, appreciate the response! :)
